services:
    BenjaminRqt\CorrelationIdBundle\EventSubscriber\CorrelationIdSubscriber:
        arguments:
            $headerName: '%correlation_id.header_name%'
        tags:
            - { name: 'kernel.event_subscriber' }

    BenjaminRqt\CorrelationIdBundle\Logger\CorrelationIdProcessor:
        arguments:
            $requestStack: '@request_stack'
            $headerName: '%correlation_id.header_name%'
        tags:
            - { name: monolog.processor }

    BenjaminRqt\CorrelationIdBundle\Http\CorrelationIdHttpClient:
        decorates: 'http_client.transport'
        decoration_priority: 10
        arguments:
            $decoratedHttpClient: '@BenjaminRqt\CorrelationIdBundle\Http\CorrelationIdHttpClient.inner'
            $requestStack: '@request_stack'
            $headerName: '%correlation_id.header_name%'
